name: localgov-micro
recipe: drupal10
config:
  webroot: web
  php: '8.1'
proxy:
  mailhog:
    - mail.localgov-micro.lndo.site
  adminer:
    - adminer.localgov-micro.lndo.site
  appserver:
    # Microsite domains
    - localgov-micro.lndo.site
    - localgov-micro-1.lndo.site
    - localgov-micro-2.lndo.site
    - localgov-micro-3.lndo.site
    - localgov-micro-4.lndo.site
    - localgov-micro-5.lndo.site
    # PHPUnit test domains
    - appserver
    - group-a1.appserver
    - group-a2.appserver
    - group-a3.appserver
    - group-b1.appserver
    - group-b2.appserver
    - group-b3.appserver
services:
  appserver:
    xdebug: true
    scanner:
      retry: 5
    build_as_root:
      # This disables Xdebug during build, but puts all dependencies in place
      # ready for the tooling to enable Xdebug.
      - rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/web'
        DRUSH_OPTIONS_URI: 'https://localgov-micro.lndo.site'
        SIMPLETEST_DB: 'mysql://database:database@database/database'
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", { "chromeOptions": { "w3c": false } }, "http://chromedriver:4444/wd/hub"]'
        BROWSERTEST_OUTPUT_DIRECTORY: '/app/web/sites/simpletest/browser_output'
        BROWSERTEST_OUTPUT_BASE_URL: 'https://localgov-micro.lndo.site'
         # Support debugging CLI with Xdebug.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION: "lando"
    build:
      - mkdir -p web/sites/simpletest/browser_output
  database:
    creds:
      user: database
      password: database
      database: database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: '/bin/s6-svscan /etc/services.d'
    portforward: true
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      expose:
        - '4444'
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
tooling:
  deprecated:
    service: appserver
    cmd: 'bash -c "/app/bin/phpstan analyse -c /app/phpstan.neon /app/web/profiles/contrib/localgov_*/ /app/web/modules/contrib/localgov_*/  /app/web/themes/contrib/localgov_*"'
  drush:
    service: appserver
    cmd: '/app/bin/drush'
  phpcs:
    service: appserver
    cmd: '/app/bin/phpcs'
  phix:
    service: appserver
    cmd: '/app/bin/phpcbf'
  phpstan:
    service: appserver
    cmd: '/app/bin/phpstan'
  phpunit:
    service: appserver
    cmd: '/app/bin/phpunit --testdox'
  xdebug-on:
    service: appserver
    description: Enable Xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Xdebug enabled"
    user: root
  xdebug-off:
    service: appserver
    description: Disable Xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Xdebug disabled"
    user: root
